/*
 * File: app/view/RootViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Dashboard.view.RootViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.rootviewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column'
    ],

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Markets'
                        },
                        {
                            xtype: 'panel',
                            title: 'Settings'
                        },
                        {
                            xtype: 'panel',
                            layout: 'border',
                            title: 'Account',
                            items: [
                                {
                                    xtype: 'container',
                                    region: 'center',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            width: 150,
                                            title: 'Account Details',
                                            store: 'AccountDetailsStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'item',
                                                    text: 'Item'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'value',
                                                    text: 'Value'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            flex: 1,
                                            width: 150,
                                            title: 'Account Funds',
                                            store: 'AccountFundsStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'item',
                                                    text: 'Item'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'value',
                                                    text: 'Value'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'south',
                                    height: 150,
                                    title: 'Account Statement',
                                    store: 'AccountStatementStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'refId',
                                            text: 'Ref Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'amount',
                                            text: 'Amount'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'balance',
                                            text: 'Balance'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'itemClass',
                                            text: 'Item Class'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'itemDate',
                                            text: 'Item Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'avgPrice',
                                            text: 'Avg Price'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'betCategoryType',
                                            text: 'Bet Category Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'betSize',
                                            text: 'Bet Size'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'betType',
                                            text: 'Bet Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'commissionRate',
                                            text: 'Commission Rate'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'eventId',
                                            text: 'Event Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'eventTypeId',
                                            text: 'Event Type Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'fullMarketName',
                                            text: 'Full Market Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'grossBetAmount',
                                            text: 'Gross Bet Amount'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'marketName',
                                            text: 'Market Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'marketType',
                                            text: 'Market Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'placedDate',
                                            text: 'Placed Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'selectionId',
                                            text: 'Selection Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'selectionName',
                                            text: 'Selection Name'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'startDate',
                                            text: 'Start Date'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'transactionId',
                                            text: 'Transaction Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'transactionType',
                                            text: 'Transaction Type'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'winLose',
                                            text: 'Win Lose'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});